services:
  ttd:
    platform: linux/amd64
    container_name: ttd
    hostname: ttd
    build: .
    command: ["streamlit", "run", "app/main.py", "--server.port=8501"]
    env_file:
      - ./.env
    ports:
      - "8501:8501"
    volumes:
      - ./app:/madds-ttd/app
    networks:
      - local-network

  sqlserver:
    platform: linux/amd64
    container_name: sqlserver
    hostname: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
    environment:
      SA_PASSWORD: "MyS3cr3tP@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./app/data:/var/opt/mssql/backup
    networks:
      - local-network

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
