services:
  ttd:
    platform: linux/amd64
    container_name: ttd
    hostname: ttd
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - ./.env
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./app:/madds-ttd/app
    networks:
      - local-network

  postgres:
    platform: linux/amd64
    container_name: postgres
    hostname: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
